### ISSUE TITLE
Provide an option to create new Textures for SaveGame Thumbnails

### ISSUE THREAD

**Issue by JaXt0r** [GothicKit/ZenKitCS#14]
## Description
When a SaveGame is created, a Thumbnail of the current view can be stored alongside. Currently, there is no suitable constructor for ZenKit.Texture to create an empty one and provide it to ZenKit.SaveGame.Save() logic.

```c#
var save = new SaveGame(GameVersion.Gothic1);
save.Thumbnail = new ZenKit.Texture(); // Compile time error as no such Constructor exists.
```

## Expected behaviour
It seems the easiest way is to
1. instead of expecting a _Texture_ for _Thumbnail_, we could expect the _ITexture_ interface. With this, we could create a _ZenKit.CachedTexture_ on our side and fill it with data.

Hint: But we need to be sure, that SaveGame.Save isn't using any Handle logic as this UIntPtr is empty.

## Source code references:
* [ZenKit.Texture constructors](https://github.com/GothicKit/ZenKitCS/blob/main/ZenKit/Texture.cs#L112-L134)
* [ZenKit.CachedTexture class](https://github.com/GothicKit/ZenKitCS/blob/main/ZenKit/Texture.cs#L48)
* [ZenKit.SaveGame.Thumbnail field](https://github.com/GothicKit/ZenKitCS/blob/main/ZenKit/SaveGame.cs#L426-L434)

**Comment by lmichaelis** [comment]
Since textures aren't quite that easy, there needs to be a separate API to create them. That API already exists [in C++](https://github.com/GothicKit/ZenKit/blob/main/include%2Fzenkit%2FTexture.hh#L154), but is largely untested. I have already begun the process of porting it to C and then C#, but that's not yet finished.

I'll keep you updated.

**Comment by lmichaelis** [comment]
Now that I had some time to look at this, it turns out that actually, I've already implemented it in C#

https://github.com/GothicKit/ZenKitCS/blob/4dd0843f02c46e54b7e0c72ca407282b6bfb4e98/ZenKit/Texture.cs#L255-L277

Usage:

```c#
using ZenKit;

var tb = new TextureBuilder(2, 2);
tb.AddMipmap(new byte[] {0xFF, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0xFF, 0xFF, 0xFF}, TextureFormat.R8G8B8);

var tex = tb.Build(TextureFormat.R8G8B8);
```

Mipmaps are added from highest to lowest level. Thus, with a texture of size 16x16, the first call to `AddMipmap` should contain 16x16 pixes the size of which is determined by the given format. Any other calls to `AddMipmap` are optional but can be done by providing lower resolution textures.

Each subsequent call must halve the size of the images edges, so 16x16 -> 8x8 -> 4x4 -> 2x2 -> 1x1.

**Comment by JaXt0r** [comment]
It works. Thank you. Feel free to put this information also into your README for Textures: https://zk.gothickit.dev/library/api/texture/
